### ISSUE TITLE
Navi Setup Not Building DB Tables

### ISSUE THREAD

**Issue by liceaga** [packetchaos/navi#12]
I recently pulled down the latest version of navi and it appears that there was a breaking change. The DB table _keys_ isn't being created. Any `navi` command results in the following, even when I attempted to set up the keys. I have tried the pypi package and docker image, both result in the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/navi", line 5, in <module>
    from navi.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/navi/cli.py", line 2, in <module>
    from .plugins import plugin_loader
  File "/usr/local/lib/python3.8/dist-packages/navi/plugins/__init__.py", line 2, in <module>
    from .find import find
  File "/usr/local/lib/python3.8/dist-packages/navi/plugins/find.py", line 9, in <module>
    tio = tenb_connection()
  File "/usr/local/lib/python3.8/dist-packages/navi/plugins/api_wrapper.py", line 17, in tenb_connection
    cur.execute("SELECT * from keys;")
sqlite3.OperationalError: no such table: keys
```

**Comment by packetchaos** [comment]
I'll get this fixed tonight.  Looking at it now.

**Comment by packetchaos** [comment]
I pulled the latest version, 6.1.1, and went through some testing and could not replicate the problem you are seeing.

Did you run the `navi keys` command and enter your tenable.io keys?

**Comment by packetchaos** [comment]
Okay I found it.  My test scripts start with the DB already created...I've fixed that.

the new version should work now. 6.1.2

Thank you for reporting the issue!
