### ISSUE TITLE
navi display agents throws error after subset of data

### ISSUE THREAD

**Issue by mroshan1** [packetchaos/navi#15]
When trying to display agent, i get following error after it returns a subset of data. . Appreciate if you can take a look and suggest a fix. 

Thanks

```
% navi display agents | more
Hey Listen!

Agent Name                                     IP Address           Last Connect Time    Last Scanned Time    Status     Groups
------------------------------------------------------------------------------------------------------------------------------------------------------
alation-prod                                   x.x.x.x           Nov 10 13:05:57      Nov 09 16:41:24      on          IT Engineering
..
elastic5.ec2.packerbuild                       x.x.xx          Nov 09 02:26:09      Not Scanned          off

Traceback (most recent call last):
  File "/Users//Documents/src/navi/venv-navi/bin/navi", line 11, in <module>
    load_entry_point('navi-pro==6.1.8', 'console_scripts', 'navi')()
  File "/Users//Documents/src/navi/venv-navi/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users//Documents/src/navi/venv-navi/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users//Documents/src/navi/venv-navi/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users//Documents/src/navi/venv-navi/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users//Documents/src/navi/venv-navi/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users//Documents/src/navi/venv-navi/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users//Documents/src/navi/venv-navi/lib/python3.8/site-packages/navi_pro-6.1.8-py3.8.egg/navi/plugins/display.py", line 211, in agents
KeyError: 'last_connect'
```

**Comment by packetchaos** [comment]
I'll resolve these as well. Keep them coming. ;)

I'll have them resolved tonight.

**Comment by mroshan1** [comment]
Thank you, I find your tool very helpful. I think you must have gone through same pain points that we are facing, hence trying to report these to make the tool really useful for a bigger community.
