### ISSUE TITLE
Find Assets with Credential Issues using plugin 104410

### ISSUE THREAD

**Issue by vinaykumarreddyrajannagari** [packetchaos/navi#21]
Below is the error when trying to find assets with Credential Issues

[centos@zmap-server navi-pro]$ navi find creds

Below are the Assets that have had Credential issues

Plugin   IP Address       FQDN                                           UUID                                     Network UUID
------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/navi", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/navi/plugins/find.py", line 159, in creds
    find_by_plugin(104410)
  File "/usr/local/lib/python3.6/site-packages/navi/plugins/find.py", line 18, in find_by_plugin
    click.echo("{:8s} {:16s} {:46s} {:40s} {}".format(str(pid), row[0], textwrap.shorten(row[2], 46), row[1], row[3]))
  File "/usr/lib64/python3.6/textwrap.py", line 406, in shorten
    return w.fill(' '.join(text.strip().split()))
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by packetchaos** [comment]
Can you perform a "navi update full" and try again?

I think this is a simple error correction problem based on the 'NoneType' error, but I want to confirm.

Also, ensure that you are an admin in T.io as some endpoints may not function properly with out being an admin.

**Comment by packetchaos** [comment]
Are you still having issues.  Please re-open the ticket if you are still having issues,
